<?php

namespace App\Notifications;

use App\Models\FinancialReport;
use App\Models\Notification as AppNotification;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

class FinancialReportNotification extends Notification implements ShouldQueue
{
    use Queueable;

    public function __construct(
        protected FinancialReport $report
    ) {}

    /**
     * Get the notification's delivery channels.
     */
    public function via(object $notifiable): array
    {
        $channels = [];
        
        if ($notifiable->shouldReceiveNotification(AppNotification::TYPE_FINANCIAL_REPORT, 'email')) {
            $channels[] = 'mail';
        }
        
        if ($notifiable->shouldReceiveNotification(AppNotification::TYPE_FINANCIAL_REPORT, 'in_app')) {
            $channels[] = 'database';
        }
        
        return $channels;
    }

    /**
     * Get the mail representation of the notification.
     */
    public function toMail(object $notifiable): MailMessage
    {
        $reportType = $this->report->type_display;
        $period = $this->report->start_date->format('M j') . ' - ' . $this->report->end_date->format('M j, Y');
        
        return (new MailMessage)
            ->subject("New Financial Report: {$reportType}")
            ->greeting("Hello {$notifiable->name}!")
            ->line("A new {$reportType} has been generated and is ready for download.")
            ->line("Report Period: {$period}")
            ->line("Generated by: {$this->report->generator->name}")
            ->line("Generated on: {$this->report->generated_at->format('F j, Y g:i A')}")
            ->line("Format: {$this->report->format_display}")
            ->line("File Size: {$this->report->formatted_file_size}")
            ->action('Download Report', $this->report->getDownloadUrl())
            ->line('Access your financial reports anytime through the reports section.')
            ->line('This report provides valuable insights into the group\'s financial performance.');
    }

    /**
     * Get the database representation of the notification.
     */
    public function toDatabase(object $notifiable): array
    {
        $reportType = $this->report->type_display;
        $period = $this->report->start_date->format('M j') . ' - ' . $this->report->end_date->format('M j, Y');
        
        return [
            'type' => AppNotification::TYPE_FINANCIAL_REPORT,
            'title' => "New {$reportType} Available",
            'message' => "A new {$reportType} for {$period} is ready for download.",
            'action_url' => route('reports.download', $this->report->id),
            'action_text' => 'Download Report',
            'priority' => AppNotification::PRIORITY_NORMAL,
            'data' => [
                'report_id' => $this->report->id,
                'report_type' => $this->report->type,
                'report_title' => $this->report->title,
                'start_date' => $this->report->start_date->toDateString(),
                'end_date' => $this->report->end_date->toDateString(),
                'export_format' => $this->report->export_format,
                'file_size' => $this->report->file_size,
                'generated_by' => $this->report->generator->name,
            ],
        ];
    }

    /**
     * Get the array representation of the notification.
     */
    public function toArray(object $notifiable): array
    {
        return $this->toDatabase($notifiable);
    }
}