<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Facades\Storage;

class FinancialReport extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'type',
        'start_date',
        'end_date',
        'report_data',
        'metadata',
        'status',
        'file_path',
        'export_format',
        'generated_by',
        'generated_at',
        'file_size',
        'hash',
    ];

    protected $casts = [
        'start_date' => 'date',
        'end_date' => 'date',
        'report_data' => 'array',
        'metadata' => 'array',
        'generated_at' => 'datetime',
    ];

    // Report types
    const TYPE_BALANCE_SHEET = 'balance_sheet';
    const TYPE_PROFIT_LOSS = 'profit_loss';
    const TYPE_CASH_FLOW = 'cash_flow';
    const TYPE_MEMBER_STATEMENT = 'member_statement';
    const TYPE_PAID_UP_MEMBERS = 'paid_up_members';

    // Report statuses
    const STATUS_GENERATING = 'generating';
    const STATUS_COMPLETED = 'completed';
    const STATUS_FAILED = 'failed';

    // Export formats
    const FORMAT_PDF = 'pdf';
    const FORMAT_EXCEL = 'excel';
    const FORMAT_CSV = 'csv';

    /**
     * Get the user who generated the report.
     */
    public function generator(): BelongsTo
    {
        return $this->belongsTo(User::class, 'generated_by');
    }

    /**
     * Get the file URL if it exists.
     */
    public function getFileUrl(): ?string
    {
        return $this->file_path ? Storage::url($this->file_path) : null;
    }

    /**
     * Get the download URL for the report file.
     */
    public function getDownloadUrl(): ?string
    {
        return $this->file_path ? route('reports.download', $this->id) : null;
    }

    /**
     * Get formatted file size.
     */
    public function getFormattedFileSizeAttribute(): string
    {
        if (!$this->file_size) {
            return 'N/A';
        }

        $bytes = $this->file_size;
        $units = ['B', 'KB', 'MB', 'GB'];
        
        for ($i = 0; $bytes > 1024 && $i < count($units) - 1; $i++) {
            $bytes /= 1024;
        }
        
        return round($bytes, 2) . ' ' . $units[$i];
    }

    /**
     * Get report type display name.
     */
    public function getTypeDisplayAttribute(): string
    {
        return match($this->type) {
            self::TYPE_BALANCE_SHEET => 'Balance Sheet',
            self::TYPE_PROFIT_LOSS => 'Profit & Loss Statement',
            self::TYPE_CASH_FLOW => 'Cash Flow Statement',
            self::TYPE_MEMBER_STATEMENT => 'Member Statement',
            self::TYPE_PAID_UP_MEMBERS => 'Paid-up Members Report',
            default => ucfirst(str_replace('_', ' ', $this->type)),
        };
    }

    /**
     * Get export format display name.
     */
    public function getFormatDisplayAttribute(): string
    {
        return match($this->export_format) {
            self::FORMAT_PDF => 'PDF',
            self::FORMAT_EXCEL => 'Excel',
            self::FORMAT_CSV => 'CSV',
            default => strtoupper($this->export_format),
        };
    }

    /**
     * Get status badge color.
     */
    public function getStatusColorAttribute(): string
    {
        return match($this->status) {
            self::STATUS_COMPLETED => 'success',
            self::STATUS_FAILED => 'danger',
            self::STATUS_GENERATING => 'warning',
            default => 'secondary',
        };
    }

    /**
     * Scope a query to only include reports of a specific type.
     */
    public function scopeOfType($query, string $type)
    {
        return $query->where('type', $type);
    }

    /**
     * Scope a query to only include completed reports.
     */
    public function scopeCompleted($query)
    {
        return $query->where('status', self::STATUS_COMPLETED);
    }

    /**
     * Scope a query to only include reports for a date range.
     */
    public function scopeForDateRange($query, $startDate, $endDate)
    {
        return $query->where('start_date', '>=', $startDate)
                    ->where('end_date', '<=', $endDate);
    }

    /**
     * Scope a query to only include reports generated by a specific user.
     */
    public function scopeGeneratedBy($query, $userId)
    {
        return $query->where('generated_by', $userId);
    }

    /**
     * Get all available report types.
     */
    public static function getReportTypes(): array
    {
        return [
            self::TYPE_BALANCE_SHEET => 'Balance Sheet',
            self::TYPE_PROFIT_LOSS => 'Profit & Loss Statement',
            self::TYPE_CASH_FLOW => 'Cash Flow Statement',
            self::TYPE_MEMBER_STATEMENT => 'Member Statement',
            self::TYPE_PAID_UP_MEMBERS => 'Paid-up Members Report',
        ];
    }

    /**
     * Get all available export formats.
     */
    public static function getExportFormats(): array
    {
        return [
            self::FORMAT_PDF => 'PDF',
            self::FORMAT_EXCEL => 'Excel',
            self::FORMAT_CSV => 'CSV',
        ];
    }

    /**
     * Mark the report as completed.
     */
    public function markCompleted(string $filePath, int $fileSize, string $hash): void
    {
        $this->update([
            'status' => self::STATUS_COMPLETED,
            'file_path' => $filePath,
            'file_size' => $fileSize,
            'hash' => $hash,
            'generated_at' => now(),
        ]);
    }

    /**
     * Mark the report as failed.
     */
    public function markFailed(string $errorMessage = null): void
    {
        $metadata = $this->metadata ?? [];
        if ($errorMessage) {
            $metadata['error_message'] = $errorMessage;
        }

        $this->update([
            'status' => self::STATUS_FAILED,
            'metadata' => $metadata,
        ]);
    }

    /**
     * Delete the report file from storage.
     */
    public function deleteFile(): bool
    {
        if ($this->file_path && Storage::exists($this->file_path)) {
            return Storage::delete($this->file_path);
        }
        return true;
    }

    /**
     * Delete the model and its associated file.
     */
    public function delete()
    {
        $this->deleteFile();
        return parent::delete();
    }
}